%YAML:1.0
dataset_dir: /home/tomy807/dataset/sequences/02

# camera intrinsics
camera.fx: 718.856
camera.fy: 718.856
camera.cx: 607.1928
camera.cy: 185.2157

num_features: 150
num_features_init: 50
num_features_tracking: 50
